### ISSUE TITLE
ERROR [+8231] with .txt but not with .TextGrid

### ISSUE THREAD

**Issue by ekbrown** [EricWilbanks/faseAlign#4]
Loving this software, except, I can only get it to work with .TextGrid files rather than with both .txt and .TextGrid. I'll attach the .txt file I get the error message with. (Github doesn't seem to allow me to attach the .wav file.)

  ERROR [+8231]  GetHCIModel: Cannot find hmm [???-]{[+???]
 FATAL ERROR - Terminating program HVite
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/faseAlign", line 980, in <module>
    main(args.wav, args.stereo, args.left, args.right, args.transcript, args.outpath, args.name, args.missing, args.syllables, args.prevent, args.tags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/faseAlign", line 941, in main
    output_intervals = align_from_txt(speaker_indices,speaker_list,first_speaker,tmppath,repos,basename,dict_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/faseAlign", line 818, in align_from_txt
    return output_intervals
UnboundLocalError: local variable 'output_intervals' referenced before assignment
[testing.txt](https://github.com/EricWilbanks/faseAlign/files/1624698/testing.txt)

**Comment by EricWilbanks** [comment]
This was actually a larger issue than I suspected. One set of issues was simple bug fixes which I've now implemented in version 1.1.7. 

Another culprit is the method which I handle .txt input encoding (lines below) which does not catch all BOMs or encoding types. I'll plan an overhaul of how input encodings are parsed to address this issue long term.

In the short term, you should be able to change the encoding to utf-8 without BOM using a text editor, and then use this .txt file as your input.

https://github.com/EricWilbanks/faseAlign/blob/54f9ced449575fdc94093d34b0925daac1994ff9/faseAlign/faseAlign#L930-L941

**Comment by akshatdewan** [comment]
Hi, 
I also get the same error, unfortunately. 
```
 ERROR [+8231]  GetHCIModel: Cannot find hmm [???-]Ã´[+???]
 FATAL ERROR - Terminating program HVite
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/faseAlign", line 841, in <module>
    main(args.wav, args.stereo, args.left, args.right, args.transcript, args.outpath, args.name, args.missing, args.syllables, args.phonemicize, args.tags, args.version, args.tier)
  File "/home/ubuntu/miniconda3/bin/faseAlign", line 800, in main
    output_intervals = align_from_txt(speaker_indices,speaker_list,first_speaker,tmppath,repos,basename,dict_path)
  File "/home/ubuntu/miniconda3/bin/faseAlign", line 676, in align_from_txt
    return output_intervals
UnboundLocalError: local variable 'output_intervals' referenced before assignment

```

The character encoding seems to be correct - 
```
ubuntu@BCE:~/miniconda3/bin$ file -i /home/ubuntu/Desktop/Shared/sf_s2t/UNHQ_data_s2t/downloadqSlwz101124/es_all_norm.txt
/home/ubuntu/Desktop/Shared/sf_s2t/UNHQ_data_s2t/downloadqSlwz101124/es_all_norm.txt: text/plain; charset=utf-8
```

Do you happen to know what I may be doing wrong? Thanks!

**Comment by akshatdewan** [comment]
I am sorry, since it was low priority I put it on the back burner and never got the time to look into it again. I will try to reproduce it and will get back.

**Comment by marialaraa** [comment]
Hi! 

Is there some news about this error? I am having the same.

**Comment by EricWilbanks** [comment]
Sorry for the long delay here.

@marcosmacedo and @akshatdewan, is this still an issue in the current version (1.1.9)? 

You can check which version you're running with `faseAlign -v`
